/-
  Engine-emitted BSD obligations (generated by experiments/engine/verify.py).

  These are STATEMENTS, not proofs. Each theorem below is a `sorry` whose
  discharge (a real construction, checked by `lake build` against Mathlib) would
  move the corresponding engine proof-graph node from `open` to `proven`. No
  theorem here is claimed proven; this mirrors the skeleton's stance.

  Each obligation cites its engine node key, regime, and the frontier support set
  the engine computed. `engine_rankTwoObject_obligation` restates the open
  frontier object and corresponds to `BSD.rankTwoCertificate`.
-/

import BSD.StrongBSD

namespace BSD

/-- Engine node `rank_two_object` (regime rank_ge2, status open).
    Direction-01 construction: on a rank >= 2 curve, produce two provably independent rational points with det of the height regulator > 0. OPEN.
    Frontier support set (what would discharge it): { rank_two_object }.
    Discharge: a construction or proof, checked by `lake build`; only then does the node become proven.
    Corresponds to `BSD.rankTwoCertificate`. -/
theorem engine_rankTwoObject_obligation (E : RationalEC) (_h : 2 ≤ analyticRank E) :
    2 ≤ mordellWeilRank E := by
  sorry

/-- Engine node `weak_bsd_rank_ge2` (regime rank_ge2, status open).
    ord_{s=1} L(E,s) = rank E(Q) in analytic rank >= 2. OPEN.
    Frontier support set (what would discharge it): { rank_two_object }.
    Discharge: a construction or proof, checked by `lake build`; only then does the node become proven.
    Corresponds to `BSD.weakBSD (open regime)`. -/
theorem engine_weakBSD_rankGe2_obligation (E : RationalEC) (_h : 2 ≤ analyticRank E) :
    analyticRank E = mordellWeilRank E := by
  sorry

/-- Engine node `strong_bsd_rank_ge2` (regime rank_ge2, status open).
    Strong BSD leading-coefficient formula in analytic rank >= 2. OPEN.
    Frontier support set (what would discharge it): { higher_euler_system, rank_two_object }.
    Discharge: a construction or proof, checked by `lake build`; only then does the node become proven.
    Corresponds to `BSD.strongBSD (open regime)`. -/
theorem engine_strongBSD_rankGe2_obligation (E : RationalEC) (_h : 2 ≤ analyticRank E) :
    leadingCoefficient E
      = (realPeriod E * regulator E * (tamagawaProduct E : ℝ) * (shaOrder E : ℝ))
        / ((torsionOrder E : ℝ) ^ 2) := by
  sorry

-- PENDING (not emitted as theorems, no skeleton API yet):
--   finite_sha_rank_ge2: no Tate-Shafarevich TYPE in the skeleton (only shaOrder : Nat presupposing finiteness), so finiteness is not yet expressible. Pending a `Sha` type.

end BSD
